# -*- coding: utf-8 -*-
"""day.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKWJrjlCfj2FHz2m_Nffn5K3kXNkdikN
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

data=sns.load_dataset('tips')

data_en=pd.get_dummies(data,columns=['day'],drop_first=True)

X=data_en[['total_bill','size','day_Fri', 'day_Sat', 'day_Sun']]
y=data_en['tip']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

coef_names = X.columns
for name, coef in zip(coef_names, model.coef_):
    print(f"{name} → ضریب: {coef:.2f}")

print(f"intercept → مقدار ثابت: {model.intercept_:.2f}")

day_coefs = {
    "total_bill"
    "Friday": model.coef_[2],
    "Saturday": model.coef_[3],
    "Sunday": model.coef_[4]
}

plt.figure(figsize=(6,4))
plt.bar(day_coefs.keys(), day_coefs.values(), color='skyblue')
plt.title('تأثیر روزهای هفته بر میزان انعام (ضریب رگرسیون)')
plt.ylabel('ضریب (اثر بر tip)')
plt.xlabel('روز هفته')
plt.grid(True, axis='y')
plt.show()